language: php

sudo: false

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

install:
    - composer self-update
    - composer install --no-interaction --prefer-source

script:
    - ./vendor/bin/phpcs -n